### PR TITLE
Handling of wxMemoryBuffer is improved to avoid unnecessary dependence

### PR DESCRIPTION
**Pull request by toshinagata**
I hope this helps to solve Issue #63 .

### CODE REVIEW

**Comment by pkulchenko** [comment]
@ildar, does this patch fix the compilation issue?

**Comment by pkulchenko** [comment]
@toshinagata, thank you for the changes. They look good to me; I'll just wait for @ildar to confirm it fixed the compilation issue.

**Comment by ildar** [comment]
Guys, I confirm this PR fixed the underlinking issue. And I don't see
anything broken with it.
Thanks.

**Comment by pkulchenko** [comment]
Thank you for checking and to @toshinagata for providing the patch! Merged the changes...

**Pull request merged**
