### PR TITLE
Removed webview because it is broken in wxWidgets

### PR DESCRIPTION
**Pull request by Mailaender**
New attempt https://github.com/pkulchenko/wxlua/pull/9 which now works on @openSUSE Tumbleweed rolling release as well. See https://build.opensuse.org/request/show/556607 for an integration test.

### CODE REVIEW

**Comment by Mailaender** [comment]
I marked it as `PATCH-FIX-OPENSUSE` but still submitted it here, because
* this is the easiest way to create patches for me
* actually I am not sure if this is helpful as I don't know the wxWidgets API's future

Feel free to reject this.

**Comment by pkulchenko** [comment]
@Mailaender, can you remind me how webview is broken? I couldn't find any details in the request you posted earlier...

**Comment by Mailaender** [comment]
According to https://build.opensuse.org/request/show/556640 the webkit integration was removed as it crashes applications in openSUSE. https://bugzilla.suse.com/show_bug.cgi?id=1055659 has some more details. It looks like it was deemed insecure and unmaintained.

**Comment by pkulchenko** [comment]
@Mailaender, thank you for the details! I think something like this should limit the changes to Unix-only:

```cmake
if (NOT DEFINED wxWidgets_COMPONENTS)
    if (UNIX)
      set(wxWidgets_COMPONENTS gl xrc xml net media propgrid richtext aui stc html adv core base)  # complete set for static lib/dll
    else()
      set(wxWidgets_COMPONENTS webview gl xrc xml net media propgrid richtext aui stc html adv core base)  # complete set for static lib/dll
    endif()
    #set(wxWidgets_COMPONENTS gl xrc xml net media propgrid richtext aui stc html adv core base) # for multilib/dll
    #set(wxWidgets_COMPONENTS stc mono) # for monolithic
endif()
```

**Comment by pkulchenko** [comment]
@Mailaender, I merged a slightly modified patch and pushed the changes to https://github.com/pkulchenko/wxlua/tree/wxwidgets312 branch (along with all the other recent fixes). This should compile against wxwidgets 3.1.1, 3.1.2, and the most recent master branch (3.1.1).

**Pull request closed without merging**
