### PR TITLE
Add wxpropgrid binding

### PR DESCRIPTION
**Pull request by Ruin0x11**
I'm not sure about the ownership for some of the class methods, but the propgrid example seems to run okay (except for a few missing features). It should be good enough for basic usage.

### CODE REVIEW

**Comment by pkulchenko** [comment]
Great patch!

Are there any version-related requirements (in case some objects or methods are added in some specific wxwidgets versions)?

**Comment by Ruin0x11** [comment]
I'm not sure yet, I'll have to do some blaming to find out and add all the annotations.

**Comment by pkulchenko** [comment]
You may not need to run "blame", as you can check `wxwidgets/interface/propgrid/*.h` files, as they usually have `@since` tag that indicates when a method/class was introduced. Old methods are not marked, but many of those introduced since 3.x are.

**Comment by pkulchenko** [comment]
Also, thank you for the examples and tests! I plan on squashing the commits into one, but will keep the authorship.

**Comment by pkulchenko** [comment]
@Ruin0x11, btw, I'm getting a linker failure:

```
CMakeFiles/wxLuaModule.dir/objects.a(wxcore_gdi.cpp.obj):wxcore_gdi.cpp:(.text+0x12fa3): undefined reference to `operator<<(wxFont&, wxVariant const&)'
```

Any idea where it may be coming from?

Also, the beginning of `wxcore_gdi.i` looks incorrect:

```
#if
"#if !defined(wxUSE_WEBVIEW)\n"..
"    #define wxUSE_WEBVIEW 0\n"..
"#endif\n"
```

This is most likely coming from the update you applied to `genwxbind.lua` (9145389a).

**Comment by pkulchenko** [comment]
@Ruin0x11, one more thing to check: what version of wxwidgets are you using? Is it the latest one (the current master)?

Also, any ideas on where `#if !defined(wxUSE_WEBVIEW)\n` I mentioned earlier may be coming from?

**Comment by Ruin0x11** [comment]
Yes, I used latest `master` for wxWidgets.

I don't remember adding the new define anywhere. In `wxcore_gdi.i`, I needed to add a new static method so that `wxFont` could be created from a `wxVariant`, but only if `wxPropertyView` was being used, since that's where the new variant code was added for `wxFont`.

**Comment by pkulchenko** [comment]
@Ruin0x11, I think the undefined reference in my case comes from `v << *pVariant` calls in the code you added to `wxpropgrid_override.hpp` and `wxcore_override.hpp`. Are there any alternatives I can use? I don't see where that operator is defined (or is supposed to be defined). Maybe you have some local changes that you haven't checked in?

**Comment by pkulchenko** [comment]
@Ruin0x11, do you know where the operator used in `v << *pVariant` calls is defined? My local compilation fails on it being undefined.

**Comment by Ruin0x11** [comment]
I believe for `wxFont` it's here: https://github.com/wxWidgets/wxWidgets/blob/db3e54b3dc5a4af812dea6e3945a2339ab01cbe2/include/wx/propgrid/propgriddefs.h#L598

It's unusual since it's `wxpropgrid` that's declaring the variant, instead of the header file containing `wxFont`.

**Comment by pkulchenko** [comment]
@Ruin0x11, I'd like to merge this, but I still can't compile it. What will we be missing if I remove those methods that use `v << *pVariant` syntax? Also, what version of gcc/compiler are you using?

**Comment by Ruin0x11** [comment]
It's one line in the propgrid example that calls `local font = wx.wxFont.FromVariant(value)` to support font values in a drop-down box. I'm using Visual Studio 2019 for compilation.

**Comment by pkulchenko** [comment]
@Ruin0x11, I managed to compile everything, but I had to remove the couple of methods (including `wxFont.FromVariant`). Here is my diff. Does it break anything significant for you? If not, I'd be interested in merging it along with your changes.

```patch
diff --git a/wxLua/bindings/wxwidgets/wxcore_gdi.i b/wxLua/bindings/wxwidgets/wxcore_gdi.i
index dbb5dc9..ff4f8bd 100644
--- a/wxLua/bindings/wxwidgets/wxcore_gdi.i
+++ b/wxLua/bindings/wxwidgets/wxcore_gdi.i
@@ -7,11 +7,6 @@
 // wxWidgets:   Updated to 2.8.4
 // ===========================================================================
 
-#if
-"#if !defined(wxUSE_WEBVIEW)\n"..
-"    #define wxUSE_WEBVIEW 0\n"..
-"#endif\n"
-
 // ---------------------------------------------------------------------------
 // wxPoint
 
@@ -432,9 +427,6 @@ class %delete wxFont : public wxGDIObject
     %wxchkver_3_0_0 wxFont(const wxSize& pixelSize, wxFontFamily family, wxFontStyle style, wxFontWeight weight, bool underline = false, const wxString& faceName = wxEmptyString, wxFontEncoding encoding = wxFONTENCODING_DEFAULT);
     %wxchkver_3_0_0 wxFont(const wxString& nativeInfoString);
     %wxchkver_3_0_0 wxFont(const wxNativeFontInfo& nativeInfo);
-#if wxUSE_PROPGRID && wxLUA_USE_wxPropertyGrid
-    static wxFont FromVariant(const wxVariant* pVariant);
-#endif
     %wxchkver_3_1_0 wxFont GetBaseFont() const;
     %wxchkver_3_0_0 wxFontEncoding GetEncoding() const;
     wxString GetFaceName() const;
@@ -668,7 +660,6 @@ class %delete wxColour : public wxGDIObject
     wxColour(const wxString& colourName);
     %wxchkver_3_0_0 wxColour(unsigned long colRGB);
     wxColour(const wxColour& colour);
-    static wxColour FromVariant(const wxVariant* pVariant);
     %wxchkver_2_8 unsigned char Alpha() const;
     unsigned char Blue() const;
     %wxchkver_2_8 virtual wxString GetAsString(long flags = wxC2S_NAME | wxC2S_CSS_SYNTAX) const;
diff --git a/wxLua/bindings/wxwidgets/wxcore_override.hpp b/wxLua/bindings/wxwidgets/wxcore_override.hpp
index 92ab2a0..2dc7640 100644
--- a/wxLua/bindings/wxwidgets/wxcore_override.hpp
+++ b/wxLua/bindings/wxwidgets/wxcore_override.hpp
@@ -1422,32 +1422,6 @@ static int LUACALL wxLua_wxRegionIterator_Next(lua_State *L)
 }
 %end
 
-#if wxUSE_PROPGRID && wxLUA_USE_wxPropertyGrid
-
-%override wxLua_wxFont_FromVariant
-//    static wxFont FromVariant(const wxVariant* pVariant);
-static int LUACALL wxLua_wxFont_FromVariant(lua_State *L)
-{
-    wxVariant * pVariant = (wxVariant *)wxluaT_getuserdatatype(L, 1, wxluatype_wxVariant);
-
-    if (!pVariant->IsType("wxFont")) {
-        wxlua_error(L, "Variant is not of type 'wxFont'");
-        return 0;
-    }
-
-    wxFont v;
-    v << *pVariant;
-
-    wxFont* returns = new wxFont(v);
-    wxluaO_addgcobject(L, returns, wxluatype_wxFont);
-    wxluaT_pushuserdatatype(L, returns, wxluatype_wxFont);
-
-    return 1;
-}
-%end
-
-#endif
-
 %override wxLua_wxFontMapper_GetAltForEncoding
 // bool GetAltForEncoding(wxFontEncoding encoding, wxFontEncoding *altEncoding, const wxString &faceName = wxEmptyString, bool interactive = true)
 static int LUACALL wxLua_wxFontMapper_GetAltForEncoding(lua_State *L)
@@ -1475,28 +1449,6 @@ static int LUACALL wxLua_wxFontMapper_GetAltForEncoding(lua_State *L)
 }
 %end
 
-%override wxLua_wxColour_FromVariant
-//    static wxColour FromVariant(const wxVariant* pVariant);
-static int LUACALL wxLua_wxColour_FromVariant(lua_State *L)
-{
-    const wxVariant * pVariant = (const wxVariant *)wxluaT_getuserdatatype(L, 1, wxluatype_wxVariant);
-
-    if (!pVariant->IsType("wxColour")) {
-        wxlua_error(L, "Variant is not of type 'wxColour'");
-        return 0;
-    }
-
-    wxColour v;
-    v << *pVariant;
-
-    wxColour* returns = new wxColour(v);
-    wxluaO_addgcobject(L, returns, wxluatype_wxColour);
-    wxluaT_pushuserdatatype(L, returns, wxluatype_wxColour);
-
-    return 1;
-}
-%end
-
 %override wxLua_wxPen_GetDashes
 // void GetDashes()
 static int LUACALL wxLua_wxPen_GetDashes(lua_State *L)
diff --git a/wxLua/bindings/wxwidgets/wxpropgrid_override.hpp b/wxLua/bindings/wxwidgets/wxpropgrid_override.hpp
index 371564d..b967017 100644
--- a/wxLua/bindings/wxwidgets/wxpropgrid_override.hpp
+++ b/wxLua/bindings/wxwidgets/wxpropgrid_override.hpp
@@ -10,28 +10,6 @@
 // ----------------------------------------------------------------------------
 
 
-%override wxLua_wxColourPropertyValue_FromVariant
-//    static wxColourPropertyValue FromVariant(const wxVariant* pVariant);
-static int LUACALL wxLua_wxColourPropertyValue_FromVariant(lua_State *L)
-{
-    const wxVariant * pVariant = (const wxVariant *)wxluaT_getuserdatatype(L, 1, wxluatype_wxVariant);
-
-    if (!pVariant->IsType("wxColourPropertyValue")) {
-        wxlua_error(L, "Variant is not of type 'wxColourPropertyValue'");
-        return 0;
-    }
-
-    wxColourPropertyValue v;
-    v << *pVariant;
-
-    wxColourPropertyValue* returns = new wxColourPropertyValue(v);
-    wxluaO_addgcobject(L, returns, wxluatype_wxColourPropertyValue);
-    wxluaT_pushuserdatatype(L, returns, wxluatype_wxColourPropertyValue);
-
-    return 1;
-}
-%end
-
 %override wxLua_wxPGVIteratorBase_delete_function
 // delete is private in wxPGVIteratorBase
 void wxLua_wxPGVIteratorBase_delete_function(void** p)
diff --git a/wxLua/bindings/wxwidgets/wxpropgrid_propgrid.i b/wxLua/bindings/wxwidgets/wxpropgrid_propgrid.i
index eef1832..cd11078 100644
--- a/wxLua/bindings/wxwidgets/wxpropgrid_propgrid.i
+++ b/wxLua/bindings/wxwidgets/wxpropgrid_propgrid.i
@@ -630,8 +630,6 @@ class %delete wxColourPropertyValue : public wxObject
 
     wxColour    m_colour;
 
-    static wxColourPropertyValue FromVariant(const wxVariant* pVariant);
-
     wxColourPropertyValue();
     wxColourPropertyValue( const wxColourPropertyValue& v );
     wxColourPropertyValue( const wxColour& colour );
diff --git a/wxLua/modules/wxbind/src/wxcore_gdi.cpp b/wxLua/modules/wxbind/src/wxcore_gdi.cpp
index a24c844..177e9c8 100644
--- a/wxLua/modules/wxbind/src/wxcore_gdi.cpp
+++ b/wxLua/modules/wxbind/src/wxcore_gdi.cpp
@@ -4200,34 +4200,6 @@ static int LUACALL wxLua_wxFont_Bold(lua_State *L)
 
 #endif // ((wxCHECK_VERSION(3,0,0)) && (wxLUA_USE_wxFont)) && (wxLUA_USE_wxFont)
 
-#if (((wxLUA_USE_wxFont) && (wxUSE_PROPGRID && wxLUA_USE_wxPropertyGrid)) && (wxLUA_USE_wxFont)) && (wxUSE_VARIANT)
-static wxLuaArgType s_wxluatypeArray_wxLua_wxFont_FromVariant[] = { &wxluatype_wxVariant, NULL };
-static int LUACALL wxLua_wxFont_FromVariant(lua_State *L);
-static wxLuaBindCFunc s_wxluafunc_wxLua_wxFont_FromVariant[1] = {{ wxLua_wxFont_FromVariant, WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, 1, 1, s_wxluatypeArray_wxLua_wxFont_FromVariant }};
-// %override wxLua_wxFont_FromVariant
-//    static wxFont FromVariant(const wxVariant* pVariant);
-static int LUACALL wxLua_wxFont_FromVariant(lua_State *L)
-{
-    wxVariant * pVariant = (wxVariant *)wxluaT_getuserdatatype(L, 1, wxluatype_wxVariant);
-
-    if (!pVariant->IsType("wxFont")) {
-        wxlua_error(L, "Variant is not of type 'wxFont'");
-        return 0;
-    }
-
-    wxFont v;
-    v << *pVariant;
-
-    wxFont* returns = new wxFont(v);
-    wxluaO_addgcobject(L, returns, wxluatype_wxFont);
-    wxluaT_pushuserdatatype(L, returns, wxluatype_wxFont);
-
-    return 1;
-}
-
-
-#endif // (((wxLUA_USE_wxFont) && (wxUSE_PROPGRID && wxLUA_USE_wxPropertyGrid)) && (wxLUA_USE_wxFont)) && (wxUSE_VARIANT)
-
 #if ((wxCHECK_VERSION(3,1,0)) && (wxLUA_USE_wxFont)) && (wxLUA_USE_wxFont)
 static wxLuaArgType s_wxluatypeArray_wxLua_wxFont_GetBaseFont[] = { &wxluatype_wxFont, NULL };
 static int LUACALL wxLua_wxFont_GetBaseFont(lua_State *L);
@@ -5875,10 +5847,6 @@ wxLuaBindMethod wxFont_methods[] = {
     { "Bold", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_wxFont_Bold, 1, NULL },
 #endif // ((wxCHECK_VERSION(3,0,0)) && (wxLUA_USE_wxFont)) && (wxLUA_USE_wxFont)
 
-#if (((wxLUA_USE_wxFont) && (wxUSE_PROPGRID && wxLUA_USE_wxPropertyGrid)) && (wxLUA_USE_wxFont)) && (wxUSE_VARIANT)
-    { "FromVariant", WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, s_wxluafunc_wxLua_wxFont_FromVariant, 1, NULL },
-#endif // (((wxLUA_USE_wxFont) && (wxUSE_PROPGRID && wxLUA_USE_wxPropertyGrid)) && (wxLUA_USE_wxFont)) && (wxUSE_VARIANT)
-
 #if ((wxCHECK_VERSION(3,1,0)) && (wxLUA_USE_wxFont)) && (wxLUA_USE_wxFont)
     { "GetBaseFont", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_wxFont_GetBaseFont, 1, NULL },
 #endif // ((wxCHECK_VERSION(3,1,0)) && (wxLUA_USE_wxFont)) && (wxLUA_USE_wxFont)
@@ -7466,34 +7434,6 @@ static int LUACALL wxLua_wxColour_ChangeLightness(lua_State *L)
 
 #endif // ((wxCHECK_VERSION(3,0,0)) && (wxLUA_USE_wxColourPenBrush)) && (wxLUA_USE_wxColourPenBrush)
 
-#if (wxLUA_USE_wxColourPenBrush) && (wxUSE_VARIANT)
-static wxLuaArgType s_wxluatypeArray_wxLua_wxColour_FromVariant[] = { &wxluatype_wxVariant, NULL };
-static int LUACALL wxLua_wxColour_FromVariant(lua_State *L);
-static wxLuaBindCFunc s_wxluafunc_wxLua_wxColour_FromVariant[1] = {{ wxLua_wxColour_FromVariant, WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, 1, 1, s_wxluatypeArray_wxLua_wxColour_FromVariant }};
-// %override wxLua_wxColour_FromVariant
-//    static wxColour FromVariant(const wxVariant* pVariant);
-static int LUACALL wxLua_wxColour_FromVariant(lua_State *L)
-{
-    const wxVariant * pVariant = (const wxVariant *)wxluaT_getuserdatatype(L, 1, wxluatype_wxVariant);
-
-    if (!pVariant->IsType("wxColour")) {
-        wxlua_error(L, "Variant is not of type 'wxColour'");
-        return 0;
-    }
-
-    wxColour v;
-    v << *pVariant;
-
-    wxColour* returns = new wxColour(v);
-    wxluaO_addgcobject(L, returns, wxluatype_wxColour);
-    wxluaT_pushuserdatatype(L, returns, wxluatype_wxColour);
-
-    return 1;
-}
-
-
-#endif // (wxLUA_USE_wxColourPenBrush) && (wxUSE_VARIANT)
-
 #if (wxCHECK_VERSION(2,8,0)) && (wxLUA_USE_wxColourPenBrush)
 static wxLuaArgType s_wxluatypeArray_wxLua_wxColour_GetAsString[] = { &wxluatype_wxColour, &wxluatype_TNUMBER, NULL };
 static int LUACALL wxLua_wxColour_GetAsString(lua_State *L);
@@ -8099,10 +8039,6 @@ wxLuaBindMethod wxColour_methods[] = {
     { "ChangeLightness", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_wxColour_ChangeLightness, 1, NULL },
 #endif // ((wxCHECK_VERSION(3,0,0)) && (wxLUA_USE_wxColourPenBrush)) && (wxLUA_USE_wxColourPenBrush)
 
-#if (wxLUA_USE_wxColourPenBrush) && (wxUSE_VARIANT)
-    { "FromVariant", WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, s_wxluafunc_wxLua_wxColour_FromVariant, 1, NULL },
-#endif // (wxLUA_USE_wxColourPenBrush) && (wxUSE_VARIANT)
-
 #if (wxCHECK_VERSION(2,8,0)) && (wxLUA_USE_wxColourPenBrush)
     { "GetAsString", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_wxColour_GetAsString, 1, NULL },
 #endif // (wxCHECK_VERSION(2,8,0)) && (wxLUA_USE_wxColourPenBrush)
diff --git a/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp b/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp
index c57eaee..6b008d5 100644
--- a/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp
+++ b/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp
@@ -6226,34 +6226,6 @@ int wxPGMultiButton_methodCount = sizeof(wxPGMultiButton_methods)/sizeof(wxLuaBi
 // Lua MetaTable Tag for Class 'wxColourPropertyValue'
 int wxluatype_wxColourPropertyValue = WXLUA_TUNKNOWN;
 
-#if (wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID) && (wxUSE_VARIANT)
-static wxLuaArgType s_wxluatypeArray_wxLua_wxColourPropertyValue_FromVariant[] = { &wxluatype_wxVariant, NULL };
-static int LUACALL wxLua_wxColourPropertyValue_FromVariant(lua_State *L);
-static wxLuaBindCFunc s_wxluafunc_wxLua_wxColourPropertyValue_FromVariant[1] = {{ wxLua_wxColourPropertyValue_FromVariant, WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, 1, 1, s_wxluatypeArray_wxLua_wxColourPropertyValue_FromVariant }};
-// %override wxLua_wxColourPropertyValue_FromVariant
-//    static wxColourPropertyValue FromVariant(const wxVariant* pVariant);
-static int LUACALL wxLua_wxColourPropertyValue_FromVariant(lua_State *L)
-{
-    const wxVariant * pVariant = (const wxVariant *)wxluaT_getuserdatatype(L, 1, wxluatype_wxVariant);
-
-    if (!pVariant->IsType("wxColourPropertyValue")) {
-        wxlua_error(L, "Variant is not of type 'wxColourPropertyValue'");
-        return 0;
-    }
-
-    wxColourPropertyValue v;
-    v << *pVariant;
-
-    wxColourPropertyValue* returns = new wxColourPropertyValue(v);
-    wxluaO_addgcobject(L, returns, wxluatype_wxColourPropertyValue);
-    wxluaT_pushuserdatatype(L, returns, wxluatype_wxColourPropertyValue);
-
-    return 1;
-}
-
-
-#endif // (wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID) && (wxUSE_VARIANT)
-
 #if (wxLUA_USE_wxColourPenBrush) && (wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID)
 static wxLuaArgType s_wxluatypeArray_wxLua_wxColourPropertyValue_Get_m_colour[] = { &wxluatype_wxColourPropertyValue, NULL };
 static int LUACALL wxLua_wxColourPropertyValue_Get_m_colour(lua_State *L);
@@ -6496,10 +6468,6 @@ void wxLua_wxColourPropertyValue_delete_function(void** p)
 
 // Map Lua Class Methods to C Binding Functions
 wxLuaBindMethod wxColourPropertyValue_methods[] = {
-#if (wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID) && (wxUSE_VARIANT)
-    { "FromVariant", WXLUAMETHOD_METHOD|WXLUAMETHOD_STATIC, s_wxluafunc_wxLua_wxColourPropertyValue_FromVariant, 1, NULL },
-#endif // (wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID) && (wxUSE_VARIANT)
-
 #if (wxLUA_USE_wxColourPenBrush) && (wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID)
     // %member    { "Get_m_colour", WXLUAMETHOD_METHOD, s_wxluafunc_wxLua_wxColourPropertyValue_Get_m_colour, 1, NULL },
 #endif // (wxLUA_USE_wxColourPenBrush) && (wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID)
diff --git a/wxLua/modules/wxlua/wxllua.cpp b/wxLua/modules/wxlua/wxllua.cpp
index e46027d..00edfec 100644
--- a/wxLua/modules/wxlua/wxllua.cpp
+++ b/wxLua/modules/wxlua/wxllua.cpp
@@ -2037,7 +2037,6 @@ wxVariant LUACALL wxlua_getwxVarianttype(lua_State *L, int stack_idx)
         return wxVariant((wxArrayString *)wxluaT_getuserdatatype(L, stack_idx, *p_wxluatype_wxArrayString));
     else if (wxlua_iswxuserdata(L, stack_idx))
     {
-        int stack_type = wxluaT_type(L, stack_idx);
         void* p = (void*)wxlua_touserdata(L, stack_idx, false);
         return wxVariant(p);
     }
```

**Comment by pkulchenko** [comment]
I pushed all the changes along with the squashed history with your changes to this branch: https://github.com/pkulchenko/wxlua/tree/Ruin0x11-add-wxpropgrid-binding

**Comment by pkulchenko** [comment]
I fixed the conflicts and rebased against the current master, but there are still some compilation errors:

```
.../wxlua/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp: In function 'int wxLua_wxFontProperty_constructor(lua_State*)':
.../wxlua/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp:6606:118: error: taking address of rvalue [-fpermissive]
 6606 |     const wxFont * value = (argCount >= 3 ? (const wxFont *)wxluaT_getuserdatatype(L, 3, wxluatype_wxFont) : &wxFont());
      |                                                                                                                      ^
.../wxlua/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp: In function 'int wxLua_wxSystemColourProperty_constructor(lua_State*)':
.../wxlua/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp:6997:178: error: taking address of rvalue [-fpermissive]
 6997 |     const wxColourPropertyValue * value = (argCount >= 3 ? (const wxColourPropertyValue *)wxluaT_getuserdatatype(L, 3, wxluatype_wxColourPropertyValue) : &wxColourPropertyValue());
      |                                                                                                                                                                                  ^
.../wxlua/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp: In function 'int wxLua_wxDateProperty_constructor(lua_State*)':
.../wxlua/wxLua/modules/wxbind/src/wxpropgrid_bind.cpp:7846:134: error: taking address of rvalue [-fpermissive]
 7846 |     const wxDateTime * value = (argCount >= 3 ? (const wxDateTime *)wxluaT_getuserdatatype(L, 3, wxluatype_wxDateTime) : &wxDateTime());
      |                                                                                                                                      ^
```

@Ruin0x11, do you know what to do with these?

**Pull request closed without merging**
