### PR TITLE
wxRichTextCtrl and related classes are implemented

### PR DESCRIPTION
**Pull request by toshinagata**
This is a very large patch. It still contains severals TODO's left, but basically it is working (at least on my side).
I also added an example script (taken from "RichTextCtrl overview" with a little modification)

### CODE REVIEW

**Comment by pkulchenko** [comment]
@toshinagata, thank you for the patch! Do you expect me to wait until TODOs are implemented or would you prefer to merge it as is? I'd like to do a release soon, so prefer would not leave it in some incomplete state...

**Comment by toshinagata** [comment]
@pkulchenko, thank you for your comment! In fact, I am already aware of some issues for this patch besides the TODOs, so it would be better not to merge this patch as it is. You can close this PR without merging, and let me request again when the patch looks better and complete.

**Comment by pkulchenko** [comment]
I think it's fine to keep it open and you can always force push this branch if you need to make any changes to the history.

I'll wait for your update before merging.

**Comment by toshinagata** [comment]
Sure, I will be back again when a new patch is ready.

**Comment by toshinagata** [comment]
I have completed my TODO list, and have taken care of the issues found so far. I believe this patch is ready to go now.

**Comment by pkulchenko** [comment]
@toshinagata, looks good to me; thank you for the patch! I made a couple of small changes to the sample to make it run.

**Pull request merged**
